### ISSUE TITLE
dlopen failed: library "libjniopencv_core.so" not found With android X

### ISSUE THREAD

**Issue by Evsteam** [israelalagbe/FaceLocker#10]
Process: wavetech.facelocker, PID: 6377
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$4.done(AsyncTask.java:415)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:383)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:252)
        at java.util.concurrent.FutureTask.run(FutureTask.java:271)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641)
        at java.lang.Thread.run(Thread.java:923)
     Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libjniopencv_core.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
        at java.lang.System.loadLibrary(System.java:1664)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1225)
        at org.bytedeco.javacpp.Loader.load(Loader.java:983)
        at org.bytedeco.javacpp.Loader.load(Loader.java:882)
        at org.bytedeco.javacpp.opencv_core.<clinit>(opencv_core.java:10)
        at java.lang.Class.classForName(Native Method)
        at java.lang.Class.forName(Class.java:454)
        at org.bytedeco.javacpp.Loader.load(Loader.java:941)
        at org.bytedeco.javacpp.Loader.load(Loader.java:882)
        at org.bytedeco.javacpp.opencv_objdetect$CascadeClassifier.<clinit>(opencv_objdetect.java:661)
        at wavetech.facelocker.utils.StorageHelper.loadClassifierCascade(StorageHelper.java:92)
        at wavetech.facelocker.CameraActivity$1.doInBackground(CameraActivity.java:60)
        at wavetech.facelocker.CameraActivity$1.doInBackground(CameraActivity.java:57)
        at android.os.AsyncTask$3.call(AsyncTask.java:394)
        at java.util.concurrent.FutureTask.run(FutureTask.java:266)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 
     Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libopencv_imgproc.so" not found
        at java.lang.Runtime.loadLibrary0(Runtime.java:1087)
        at java.lang.Runtime.loadLibrary0(Runtime.java:1008)
        at java.lang.System.loadLibrary(System.java:1664)
        at org.bytedeco.javacpp.Loader.loadLibrary(Loader.java:1225)
        at org.bytedeco.javacpp.Loader.load(Loader.java:968)
        at org.bytedeco.javacpp.Loader.load(Loader.java:882) 
        at org.bytedeco.javacpp.opencv_core.<clinit>(opencv_core.java:10) 
        at java.lang.Class.classForName(Native Method) 
        at java.lang.Class.forName(Class.java:454) 
        at org.bytedeco.javacpp.Loader.load(Loader.java:941) 
        at org.bytedeco.javacpp.Loader.load(Loader.java:882) 
        at org.bytedeco.javacpp.opencv_objdetect$CascadeClassifier.<clinit>(opencv_objdetect.java:661) 
        at wavetech.facelocker.utils.StorageHelper.loadClassifierCascade(StorageHelper.java:92) 
        at wavetech.facelocker.CameraActivity$1.doInBackground(CameraActivity.java:60) 
        at wavetech.facelocker.CameraActivity$1.doInBackground(CameraActivity.java:57) 
        at android.os.AsyncTask$3.call(AsyncTask.java:394) 
        at java.util.concurrent.FutureTask.run(FutureTask.java:266) 
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305) 
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1167) 
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:641) 
        at java.lang.Thread.run(Thread.java:923) 

build.gradle
  defaultConfig {
            applicationId "wavetech.facelocker"
            minSdkVersion 26
            targetSdkVersion 32
            versionCode 1
            versionName "1.0"
            testInstrumentationRunner 'androidx.test.runner.AndroidJUnitRunner'

migrate with android X

**Comment by AjitGhimire** [comment]
i am also facing same error..how to solve it?

**Comment by wangweitmac777** [comment]
i am also facing same error..how to solve it?
2024-11-28 17:06:44.299 17011-19709/wavetech.facelocker E/AndroidRuntime: FATAL EXCEPTION: AsyncTask #2
    Process: wavetech.facelocker, PID: 17011
    java.lang.RuntimeException: An error occurred while executing doInBackground()
        at android.os.AsyncTask$4.done(AsyncTask.java:415)
        at java.util.concurrent.FutureTask.finishCompletion(FutureTask.java:381)
        at java.util.concurrent.FutureTask.setException(FutureTask.java:250)
        at java.util.concurrent.FutureTask.run(FutureTask.java:269)
        at android.os.AsyncTask$SerialExecutor$1.run(AsyncTask.java:305)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1137)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:637)
        at java.lang.Thread.run(Thread.java:1012)
     Caused by: java.lang.UnsatisfiedLinkError: dlopen failed: library "libjniopencv_core.so" not found

**Comment by wangweitmac777** [comment]
> i am also facing same error..how to solve it?

in your app build.gradle,add     
    ndk {
            abiFilters 'armeabi-v7a','arm64-v8a'
        }
and copy armeabi dir,named armeabi-v7a,armeabi-v8a

**Comment by AbelNebay** [comment]
Get the arm-64 bit and arm-32 from opencv-platform website...
